⚔️ Weapons:
- changed-files:
  - any-glob-to-any-file: 
    - weapons/**

⚙️ Development:
- changed-files:
  - any-glob-to-any-file: 
    - scripts/**
    - .github/labeler.yml

🎨 Image:
- changed-files:
  - any-glob-to-any-file: 
    - images/**

🦺 github-action:
- changed-files:
  - any-glob-to-any-file: .github/workflows/**